Repository datarockets/mona, pull requests merged in 2019-05, with the labels that each got.

#30 Add a note about automatic deployment to the README
  README.md
Labels: enhancement

#33 Removed useless commas and fixed regexp to resurrect mona
  scripts/communication.js
  scripts/order_water.js
Labels: bug

#41 Fix vulnerabilities
  .eslintrc
  .eslintrc.yml
  package-lock.json
  package.json
Labels: infra

#42 Move to botkit. Greeting.
  features/greeting.js
  features/greeting/index.js
  features/greeting/queries.js
  features/greeting/replies.js
  features/routes_oauth.js
  features/sample_echo.js
  features/sample_hears.js
  features/slack_features.js
  specs/greeting_spec.js
  specs/sample_hears_spec.js
Labels: BOTKIT
